server:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kastuichik-cmd/spring-config-repo
          default-label: main
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000
spring:
  kafka:
    bootstrap-servers: kafka:9092
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongo:27017/db?authSource=admin}