server:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kastuichik-cmd/spring-config-repo
          default-label: main
spring:
  kafka:
    bootstrap-servers: kafka:9092

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: "B3"
  observations:
    key-values:
      db:
        system: postgresql
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  health:
    circuitbreakers:
      enabled: true
    bulkheads:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.kafka.listener.DeadLetterPublishingRecoverer: DEBUG
    io.micrometer: DEBUG
    io.zipkin.reporter2: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000