server:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kastuichik-cmd/spring-config-repo
          default-label: main
      retry:
        max-attempts: 6
        initial-interval: 2000
        multiplier: 1.5
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000
spring:
  kafka:
    bootstrap-servers: kafka:9092