server:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kastuichik-cmd/spring-config-repo
          default-label: main
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000