global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'gateway-service:8080'

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'auth-service:8080'

  - job_name: 'book-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'book-service:8080'

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'notification-service:8080'

  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'config-server:8888'